CREATE TABLE ai_album_albums (
  id uuid PRIMARY KEY,
  user_id varchar(64) NOT NULL,
  source_project_id varchar(64),
  title varchar(200) NOT NULL,
  description text,
  status varchar(32) NOT NULL DEFAULT 'draft',
  cover_asset_id uuid,
  last_preview_asset_id uuid,
  last_preview_html_url text,
  last_preview_poster_url text,
  canvas_width integer NOT NULL DEFAULT 1080,
  canvas_height integer NOT NULL DEFAULT 1920,
  fps integer NOT NULL DEFAULT 30,
  duration_ms integer NOT NULL DEFAULT 0,
  page_count integer NOT NULL DEFAULT 0,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL,
  created_time timestamptz NOT NULL DEFAULT now(),
  updated_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_albums_user_id_id UNIQUE (user_id, id),
  CONSTRAINT uq_albums_user_source_project_id UNIQUE (user_id, source_project_id),
  CONSTRAINT ck_albums_status CHECK (status IN ('draft', 'previewed', 'rendered', 'published', 'archived', 'deleted')),
  CONSTRAINT ck_albums_canvas_width CHECK (canvas_width > 0),
  CONSTRAINT ck_albums_canvas_height CHECK (canvas_height > 0),
  CONSTRAINT ck_albums_fps CHECK (fps > 0),
  CONSTRAINT ck_albums_duration_ms CHECK (duration_ms >= 0),
  CONSTRAINT ck_albums_page_count CHECK (page_count >= 0),
  CONSTRAINT ck_albums_settings_object CHECK (jsonb_typeof(settings) = 'object')
);

CREATE TABLE ai_album_album_pages (
  id uuid PRIMARY KEY,
  user_id varchar(64) NOT NULL,
  album_id uuid NOT NULL,
  node_id varchar(128),
  page_no integer NOT NULL,
  title varchar(200),
  status varchar(32) NOT NULL DEFAULT 'draft',
  template_key varchar(128),
  duration_ms integer NOT NULL DEFAULT 3000,
  raw_html text,
  preview_asset_id uuid,
  poster_asset_id uuid,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  style jsonb NOT NULL DEFAULT '{}'::jsonb,
  transition jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL,
  created_time timestamptz NOT NULL DEFAULT now(),
  updated_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_album_pages_user_id_id UNIQUE (user_id, id),
  CONSTRAINT uq_album_pages_user_album_id UNIQUE (user_id, album_id, id),
  CONSTRAINT uq_album_pages_album_id_page_no UNIQUE (album_id, page_no),
  CONSTRAINT uq_album_pages_album_id_node_id UNIQUE (album_id, node_id),
  CONSTRAINT fk_album_pages_album FOREIGN KEY (user_id, album_id) REFERENCES ai_album_albums (user_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_album_pages_status CHECK (status IN ('draft', 'ready', 'disabled', 'deleted')),
  CONSTRAINT ck_album_pages_page_no CHECK (page_no > 0),
  CONSTRAINT ck_album_pages_duration_ms CHECK (duration_ms > 0),
  CONSTRAINT ck_album_pages_content_object CHECK (jsonb_typeof(content) = 'object'),
  CONSTRAINT ck_album_pages_style_object CHECK (jsonb_typeof(style) = 'object'),
  CONSTRAINT ck_album_pages_transition_object CHECK (jsonb_typeof(transition) = 'object')
);

CREATE TABLE ai_album_assets (
  id uuid PRIMARY KEY,
  user_id varchar(64) NOT NULL,
  album_id uuid,
  page_id uuid,
  asset_type varchar(32) NOT NULL,
  usage_type varchar(32) NOT NULL DEFAULT 'source',
  source varchar(32) NOT NULL DEFAULT 'upload',
  status varchar(32) NOT NULL DEFAULT 'available',
  oss_bucket varchar(128),
  oss_key varchar(1024) NOT NULL,
  url text NOT NULL,
  thumbnail_url text,
  file_name varchar(255),
  mime_type varchar(128),
  file_ext varchar(32),
  file_size_bytes bigint,
  width integer,
  height integer,
  duration_ms integer,
  checksum_sha256 varchar(64),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL,
  created_time timestamptz NOT NULL DEFAULT now(),
  updated_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_assets_user_id_id UNIQUE (user_id, id),
  CONSTRAINT uq_assets_user_id_oss_key UNIQUE (user_id, oss_key),
  CONSTRAINT fk_assets_album FOREIGN KEY (user_id, album_id) REFERENCES ai_album_albums (user_id, id) ON DELETE CASCADE,
  CONSTRAINT fk_assets_page FOREIGN KEY (page_id) REFERENCES ai_album_album_pages (id) ON DELETE SET NULL,
  CONSTRAINT ck_assets_asset_type CHECK (asset_type IN ('image', 'video', 'audio', 'font', 'text', 'data', 'reference_link', 'other')),
  CONSTRAINT ck_assets_usage_type CHECK (usage_type IN ('source', 'cover', 'background', 'music', 'thumbnail', 'export', 'other')),
  CONSTRAINT ck_assets_source CHECK (source IN ('upload', 'ai_generated', 'system')),
  CONSTRAINT ck_assets_status CHECK (status IN ('uploading', 'available', 'failed', 'deleted')),
  CONSTRAINT ck_assets_page_requires_album CHECK (page_id IS NULL OR album_id IS NOT NULL),
  CONSTRAINT ck_assets_file_size_bytes CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
  CONSTRAINT ck_assets_width CHECK (width IS NULL OR width > 0),
  CONSTRAINT ck_assets_height CHECK (height IS NULL OR height > 0),
  CONSTRAINT ck_assets_duration_ms CHECK (duration_ms IS NULL OR duration_ms >= 0),
  CONSTRAINT ck_assets_checksum_sha256 CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-fA-F]{64}$'),
  CONSTRAINT ck_assets_metadata_object CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE ai_album_ai_generation_logs (
  id uuid PRIMARY KEY,
  user_id varchar(64) NOT NULL,
  album_id uuid,
  page_id uuid,
  generated_asset_id uuid,
  generation_type varchar(32) NOT NULL,
  provider varchar(64) NOT NULL,
  model varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'queued',
  prompt text,
  request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  cost_amount numeric(12, 6),
  error_code varchar(128),
  error_message text,
  started_time timestamptz,
  finished_time timestamptz,
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL,
  created_time timestamptz NOT NULL DEFAULT now(),
  updated_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_ai_generation_logs_user_id_id UNIQUE (user_id, id),
  CONSTRAINT fk_ai_generation_logs_album FOREIGN KEY (album_id) REFERENCES ai_album_albums (id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_generation_logs_page FOREIGN KEY (page_id) REFERENCES ai_album_album_pages (id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_generation_logs_generated_asset FOREIGN KEY (generated_asset_id) REFERENCES ai_album_assets (id) ON DELETE SET NULL,
  CONSTRAINT ck_ai_generation_logs_generation_type CHECK (generation_type IN ('album_outline', 'page_copy', 'page_html', 'image', 'audio', 'video', 'narration', 'music', 'frame_enhance', 'other')),
  CONSTRAINT ck_ai_generation_logs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  CONSTRAINT ck_ai_generation_logs_request_payload_object CHECK (jsonb_typeof(request_payload) = 'object'),
  CONSTRAINT ck_ai_generation_logs_response_payload_object CHECK (jsonb_typeof(response_payload) = 'object'),
  CONSTRAINT ck_ai_generation_logs_prompt_tokens CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),
  CONSTRAINT ck_ai_generation_logs_completion_tokens CHECK (completion_tokens IS NULL OR completion_tokens >= 0),
  CONSTRAINT ck_ai_generation_logs_total_tokens CHECK (total_tokens IS NULL OR total_tokens >= 0),
  CONSTRAINT ck_ai_generation_logs_cost_amount CHECK (cost_amount IS NULL OR cost_amount >= 0)
);

CREATE TABLE ai_album_export_jobs (
  id uuid PRIMARY KEY,
  user_id varchar(64) NOT NULL,
  album_id uuid NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'queued',
  export_format varchar(16) NOT NULL DEFAULT 'mp4',
  render_profile varchar(64) NOT NULL DEFAULT 'mp4_1080p',
  width integer NOT NULL DEFAULT 1080,
  height integer NOT NULL DEFAULT 1920,
  fps integer NOT NULL DEFAULT 30,
  duration_ms integer,
  progress_percent numeric(5, 2) NOT NULL DEFAULT 0,
  attempt_count integer NOT NULL DEFAULT 0,
  request_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  local_output_path text,
  oss_bucket varchar(128),
  oss_key varchar(1024),
  output_url text,
  file_size_bytes bigint,
  checksum_sha256 varchar(64),
  error_code varchar(128),
  error_message text,
  queued_time timestamptz NOT NULL DEFAULT now(),
  started_time timestamptz,
  finished_time timestamptz,
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL,
  created_time timestamptz NOT NULL DEFAULT now(),
  updated_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_export_jobs_user_id_id UNIQUE (user_id, id),
  CONSTRAINT fk_export_jobs_album FOREIGN KEY (user_id, album_id) REFERENCES ai_album_albums (user_id, id) ON DELETE CASCADE,
  CONSTRAINT ck_export_jobs_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  CONSTRAINT ck_export_jobs_export_format CHECK (export_format IN ('mp4')),
  CONSTRAINT ck_export_jobs_width CHECK (width > 0),
  CONSTRAINT ck_export_jobs_height CHECK (height > 0),
  CONSTRAINT ck_export_jobs_fps CHECK (fps > 0),
  CONSTRAINT ck_export_jobs_duration_ms CHECK (duration_ms IS NULL OR duration_ms >= 0),
  CONSTRAINT ck_export_jobs_progress_percent CHECK (progress_percent >= 0 AND progress_percent <= 100),
  CONSTRAINT ck_export_jobs_attempt_count CHECK (attempt_count >= 0),
  CONSTRAINT ck_export_jobs_request_params_object CHECK (jsonb_typeof(request_params) = 'object'),
  CONSTRAINT ck_export_jobs_file_size_bytes CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
  CONSTRAINT ck_export_jobs_checksum_sha256 CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-fA-F]{64}$')
);

CREATE INDEX idx_albums_user_status_updated_time ON ai_album_albums (user_id, status, updated_time DESC);
CREATE INDEX idx_albums_user_created_time ON ai_album_albums (user_id, created_time DESC);
CREATE INDEX idx_albums_user_source_project_id ON ai_album_albums (user_id, source_project_id) WHERE source_project_id IS NOT NULL;

CREATE INDEX idx_album_pages_user_album_id ON ai_album_album_pages (user_id, album_id);
CREATE INDEX idx_album_pages_album_node_id ON ai_album_album_pages (album_id, node_id) WHERE node_id IS NOT NULL;
CREATE INDEX idx_album_pages_user_updated_time ON ai_album_album_pages (user_id, updated_time DESC);

CREATE INDEX idx_assets_user_album_created_time ON ai_album_assets (user_id, album_id, created_time DESC);
CREATE INDEX idx_assets_user_page_id ON ai_album_assets (user_id, page_id);
CREATE INDEX idx_assets_user_type_status ON ai_album_assets (user_id, asset_type, status);
CREATE INDEX idx_assets_checksum_sha256 ON ai_album_assets (checksum_sha256) WHERE checksum_sha256 IS NOT NULL;

CREATE INDEX idx_ai_generation_logs_user_album_created_time ON ai_album_ai_generation_logs (user_id, album_id, created_time DESC);
CREATE INDEX idx_ai_generation_logs_user_status_created_time ON ai_album_ai_generation_logs (user_id, status, created_time DESC);
CREATE INDEX idx_ai_generation_logs_user_generation_type_created_time ON ai_album_ai_generation_logs (user_id, generation_type, created_time DESC);

CREATE INDEX idx_export_jobs_user_album_created_time ON ai_album_export_jobs (user_id, album_id, created_time DESC);
CREATE INDEX idx_export_jobs_user_status_created_time ON ai_album_export_jobs (user_id, status, created_time DESC);
CREATE INDEX idx_export_jobs_active ON ai_album_export_jobs (status, queued_time) WHERE status IN ('queued', 'running');
